// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwdwzfydxdpelbsleobt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3ZHd6ZnlkeGRwZWxic2xlb2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NDYwMjYsImV4cCI6MjA1MjAyMjAyNn0.-PuCXXTkFO_qa4PJkCRjFBPhSQx9fe9o0FEc7HTPyHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);